In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[0:3]

array([0, 1, 2])

In [9]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [11]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr[:5] = 100

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
slice_of_arr = arr[:6]

In [15]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [16]:
slice_of_arr[:] = 99

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr_copy = arr.copy()

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy[:6] = 100

In [22]:
arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
a2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
a2d[2][1]

8

In [27]:
a2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [28]:
a2d[1:,0:2]

array([[4, 5],
       [7, 8]])

In [29]:
a2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [30]:
a2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [31]:
arr = np.arange(1,11)

In [32]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [34]:
arr < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [39]:
bool_arr = arr > 5

In [40]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [41]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [42]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [43]:
arr[arr < 3]

array([1, 2])

In [44]:
arr_2d = np.arange(50).reshape(5,10)

In [45]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [46]:
arr_2d[1:3,4:6]

array([[14, 15],
       [24, 25]])

In [47]:
arr_2d[3:,8:]

array([[38, 39],
       [48, 49]])

In [48]:
arr_2d[3:,5:7]

array([[35, 36],
       [45, 46]])

In [49]:
arr_2d[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [50]:
arr_2d[0:5]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [51]:
git init

SyntaxError: invalid syntax (2830201818.py, line 1)

In [52]:
arr = np.arange(0,11)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr +1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [58]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [59]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [60]:
arr - 10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [61]:
arr * 100 - 100

array([-100,    0,  100,  200,  300,  400,  500,  600,  700,  800,  900])

In [62]:
arr / 0

/var/folders/p2/zc212sp14zxdyvjqklws806r0000gn/T/ipykernel_11440/3942562399.py:1: RuntimeWarning: divide by zero encountered in divide
  arr / 0
/var/folders/p2/zc212sp14zxdyvjqklws806r0000gn/T/ipykernel_11440/3942562399.py:1: RuntimeWarning: invalid value encountered in divide
  arr / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [63]:
1 / arr

/var/folders/p2/zc212sp14zxdyvjqklws806r0000gn/T/ipykernel_11440/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [64]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [66]:
arr ** 23

array([                  0,                   1,             8388608,
               94143178827,      70368744177664,   11920928955078125,
        789730223053602816, 8922003266371364727,                   0,
       8500964271916320249,  200376420520689664])

In [67]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [68]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [69]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [70]:
np.log(arr)

/var/folders/p2/zc212sp14zxdyvjqklws806r0000gn/T/ipykernel_11440/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [72]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
import numpy as np

In [76]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [77]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [78]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [79]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [80]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [81]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [82]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [83]:
matrix = np.arange(9)

In [84]:
matrix.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
matrix

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [86]:
n_m = matrix.reshape(3,3)

In [87]:
n_m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
n_m[:2,:2]

array([[0, 1],
       [3, 4]])

In [89]:
n_m[1:,1:]

array([[4, 5],
       [7, 8]])

In [90]:
n_m[1:,:2]

array([[3, 4],
       [6, 7]])

In [91]:
n_m[:2,1:]

array([[1, 2],
       [4, 5]])

In [92]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [97]:
np.random.rand(1)

array([0.73367674])

In [99]:
np.random.randn(25)

array([-0.54544584, -1.2542355 ,  1.58222517,  0.59129065,  0.34250466,
       -0.10245624,  0.32616485,  0.62686798, -0.42275225,  0.41907073,
       -0.07408019, -1.12411504, -0.53623959, -0.82198763,  0.04780701,
       -0.13801589,  0.97256864, -1.16906049,  0.28030438,  1.12814611,
        0.46665909, -0.17140495, -0.2086344 , -0.38124496,  0.23247368])

In [100]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [101]:
np.arange(1,101).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [102]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [103]:
mat = np.arange(1,26).reshape(5,5)

In [104]:
mat[0,2]

3

In [105]:
mat[0]

array([1, 2, 3, 4, 5])

In [106]:
mat[0:,1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [107]:
mat[3,4]

20

In [108]:
mat[3][4]

20

In [109]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [110]:
np.arange(21,26)

array([21, 22, 23, 24, 25])

In [111]:
mat[3:,3:]

array([[19, 20],
       [24, 25]])

In [112]:
np.sum(mat)

325

In [113]:
mat.sum()

325

In [114]:
mat.std()

7.211102550927978

In [115]:
np.std(mat)

7.211102550927978

In [116]:
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])