In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[0:3]

array([0, 1, 2])

In [9]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [11]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr[:5] = 100

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
slice_of_arr = arr[:6]

In [15]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [16]:
slice_of_arr[:] = 99

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr_copy = arr.copy()

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy[:6] = 100

In [22]:
arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
a2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
a2d[2][1]

8

In [27]:
a2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [28]:
a2d[1:,0:2]

array([[4, 5],
       [7, 8]])

In [29]:
a2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [30]:
a2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [31]:
arr = np.arange(1,11)

In [32]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [34]:
arr < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [39]:
bool_arr = arr > 5

In [40]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [41]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [42]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [43]:
arr[arr < 3]

array([1, 2])

In [44]:
arr_2d = np.arange(50).reshape(5,10)

In [45]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [46]:
arr_2d[1:3,4:6]

array([[14, 15],
       [24, 25]])

In [47]:
arr_2d[3:,8:]

array([[38, 39],
       [48, 49]])

In [48]:
arr_2d[3:,5:7]

array([[35, 36],
       [45, 46]])

In [49]:
arr_2d[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [50]:
arr_2d[0:5]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [51]:
git init

SyntaxError: invalid syntax (2830201818.py, line 1)