In [35]:
import numpy as np

In [36]:
arr = np.array([1,2,3])

In [37]:
arr

array([1, 2, 3])

In [38]:
type(arr)

numpy.ndarray

In [39]:
my_arr =[[1,2,3],[4,5,6],[7,8,9]]

In [40]:
np.array(my_arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
np.arange(0,10,5)

array([0, 5])

In [45]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [56]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [62]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [64]:
np.random.rand(5)

array([0.65744924, 0.60335385, 0.87246047, 0.63747426, 0.52821916])

In [66]:
np.random.randn(2,3)

array([[-0.50231975, -0.01067316,  0.91925726],
       [-0.16058469, -0.37969244, -0.82562952]])

In [67]:
np.random.randint(1,100,10)

array([50, 24, 63,  1, 69, 44, 36, 27, 20, 60])

In [68]:
ranarr = np.random.randint(0,50,10)

In [69]:
ranarr

array([22, 15, 24,  7, 26, 48, 33, 16, 47, 22])

In [70]:
ranarr.min()

7

In [72]:
ranarr.max()

48

In [74]:
ranarr.argmax()

5

In [75]:
ranarr.argmin()

3

In [77]:
ranarr.sort()

In [78]:
print(ranarr)

[ 7 15 16 22 22 24 26 33 47 48]


In [79]:
ranarr.shape

(10,)

In [80]:
ranarr.dtype

dtype('int64')

In [9]:
s[0:5]

'hello'

In [10]:
s[-1:5]

'o'

In [11]:
s[-1]

'o'

In [12]:
s[-1:1]

''

In [13]:
s[-2]

'l'

In [14]:
s[-5]

'h'

In [15]:
s[-5:-1]

'hell'

In [16]:
s[-5:0]

''

In [17]:
# list

In [18]:
my_list = ['a','b','c','d']

In [19]:
my_list[1]

'b'

In [20]:
nest = [1,2,[3,4]]

In [21]:
nest[2][1]

4

In [22]:
d = {'key1':'value','key2':123}

In [23]:
d['key1']

'value'

In [24]:
d['key2']

123

In [25]:
d = {'key1':"value","key2":[1,2,3,4]}

In [26]:
d['key2']

[1, 2, 3, 4]

In [27]:
d = {'k1':{'innerkey':[1,2,3,4]}}

In [30]:
d['k1']['innerkey']

[1, 2, 3, 4]

In [31]:
t = (1,2,3)

In [32]:
t[0]

1

TypeError: 'tuple' object does not support item assignment

In [34]:
{1,2,3,4,4,4,4,4}

{1, 2, 3, 4}

In [ ]:
s = {1,2,3}